"""Notifier / Report Node — 結果サマリの生成 (設計書 §4.2)。

register (初期計画) / assessment (復習計画) の両経路で使う。
スキル名は PlanItem.name から引く (Planner が部分グラフから設定済み)。
"""

from app.models.schemas import PlannerOutput, SessionDraft, WeaknessOutput

_WEEKDAYS_JP = "月火水木金土日"


def build_summary(
    plan: PlannerOutput,
    sessions: list[SessionDraft] | None = None,
    schedule_warnings: list[str] | None = None,
    weakness: WeaknessOutput | None = None,
    kind: str = "review",
    deadline: str = "",
    calendar_links: dict[str, str] | None = None,
) -> str:
    names = {item.skill_id: item.name or item.skill_id for item in plan.plan}

    if kind == "initial":
        lines = ["学習対象を登録し、初期学習計画を作成しました。", ""]
    else:
        lines = ["弱点クラスタを検出し、復習計画を作成しました。", ""]
    if deadline:
        lines.insert(1, f"🎯 目標期限: {deadline}")

    if weakness is not None:
        for w in weakness.weak_skills:
            pres = ", ".join(p.name for p in w.unmastered_prerequisites) or "なし"
            lines.append(f"- {w.weak_skill_name} (スコア {w.score:.0%}) / 未習熟の前提: {pres}")
        lines.append("")

    lines.append(f"学習順序 ({len(plan.plan)} 件):")
    for item in plan.plan:
        lines.append(f"  {item.order}. {names[item.skill_id]} ({item.estimated_minutes}分)")
    for w in plan.warnings:
        lines.append(f"⚠ {w}")

    if sessions:
        lines.append("")
        lines.append(f"📅 学習スケジュール ({len(sessions)} ブロック):")
        for s in sessions:
            wd = _WEEKDAYS_JP[s.start.weekday()]
            lines.append(
                f"  {s.start:%m/%d}({wd}) {s.start:%H:%M}-{s.end:%H:%M}"
                f" {s.skill_name or names.get(s.skill_id, s.skill_id)}"
            )
    if calendar_links:
        lines.append("")
        lines.append("🗓 資格ごとの専用カレンダーに登録しました:")
        for url in calendar_links.values():
            lines.append(f"  {url}")
        lines.append("  (共有するには Google カレンダーの設定で公開してください)")
    if deadline and sessions and not schedule_warnings:
        lines.append("✅ 計画は期限内に無理なく収まっています")
    for w in schedule_warnings or []:
        lines.append(f"⚠ {w}")
    return "\n".join(lines)


def build_no_weakness_report(weakness: WeaknessOutput) -> str:
    return "今回の模試に閾値未満の弱点スキルはありませんでした。現在の計画を継続してください。"


def build_event_texts(
    skill_id: str,
    names: dict[str, str],
    kind: str,
    weakness: WeaknessOutput | None,
) -> tuple[str, str]:
    """カレンダーイベントの (タイトル, 本文) を生成する (設計書 §4.2 Scheduler)。"""
    name = names.get(skill_id, skill_id)
    summary = f"📚 SkillPath: {name}"
    lines = [f"SkillPath の{'復習' if kind == 'review' else '学習'}ブロックです。", ""]
    if weakness is not None:
        for w in weakness.weak_skills:
            if w.weak_skill_id == skill_id:
                lines.append(f"模試スコア: {w.score:.0%} — 弱点として検出されました。")
            elif any(p.id == skill_id for p in w.unmastered_prerequisites):
                lines.append(
                    f"「{w.weak_skill_name}」(スコア {w.score:.0%}) を理解するための"
                    "前提スキルとして、先に固める必要があります。"
                )
    lines.append("")
    lines.append("Generated by SkillPath (All Things Agentic Hackathon)")
    return summary, "\n".join(lines)
